io: io.c
	gcc -ggdb -O0 io.c -lmetha -o io

html: html.c
	gcc -ggdb -O0 html.c -lmetha -o html

url: url.c ../src/libmetha/url.c
	gcc -ggdb -O0 url.c ../src/libmetha/url.c -o url

conf: conf.c
	gcc -ggdb -O0 conf.c -lmetha -o conf

mtrie: mtrie.c
	gcc -ggdb -O0 mtrie.c -lmetha -o mtrie
